/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hdt.petshopproject.component.chartpanel.barchart;

import hdt.chart.ModelChart;
import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class TestBarChart extends javax.swing.JFrame {

    /**
     * Creates new form BarChart
     */
    public TestBarChart() {
        initComponents();
        getContentPane().setBackground(new Color(250, 250, 250));
        chart.addLegend("Income", new Color(245, 189, 135));
        chart.addLegend("Expense", new Color(135, 189, 245));
        chart.addLegend("Profit", new Color(189, 135, 245));
        chart.addLegend("Cost", new Color(139, 229, 222));
        chart.addData(new ModelChart("T1", new double[]{500, 200, 80,89}));
        chart.addData(new ModelChart("T2", new double[]{600, 750, 90,150}));
        chart.addData(new ModelChart("T3", new double[]{200, 350, 460,900}));
        chart.addData(new ModelChart("T4", new double[]{480, 150, 750,700}));
        chart.addData(new ModelChart("T5", new double[]{350, 540, 300,150}));
        chart.addData(new ModelChart("T6", new double[]{190, 280, 81,200}));
        chart.addData(new ModelChart("T7", new double[]{500, 200, 80,89}));
        chart.addData(new ModelChart("T8", new double[]{600, 750, 90,150}));
        chart.addData(new ModelChart("T9", new double[]{200, 350, 460,900}));
        chart.addData(new ModelChart("T10", new double[]{480, 150, 750,700}));
        chart.addData(new ModelChart("T11", new double[]{350, 540, 300,150}));
        chart.addData(new ModelChart("T12", new double[]{190, 280, 81,200}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new hdt.barchart.BarChart();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestBarChart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hdt.barchart.BarChart chart;
    // End of variables declaration//GEN-END:variables
}
